employee/urls.py
from django.conf.urls import patterns, include, url

import views

urlpatterns = patterns('',
    url(r'^stafflist/$',                                    views.stafflist_list,   name='stafflist_list'),
    url(r'^stafflist/(?P<id>\d+)/$',                        views.stafflist_view,   name='stafflist_view'),
    url(r'^staff/(?P<list_id>\d+)/(?P<spec_id>\d+)/add/$',  views.staff_add,        name='staff_add'),
    url(r'^staff/(?P<id>\d+)/edit/$',                       views.staff_edit,       name='staff_edit'),
    url(r'^staff/(?P<id>\d+)/del/$',                        views.staff_del,        name='staff_del'),
    url(r'^employee/$',                                     views.employee_list,    name='employee_list'),
    url(r'^employee/(?P<id>\d+)/$',	                        views.employee_view,    name='employee_view'),
    url(r'^rs_r/$',                                         views.rs_room_auto,     name='rs_room_auto'),
    url(r'^rs_r/(?P<rs_id>\d+)/(?P<room_id>\d+)/$',         views.rs_room,          name='rs_room'),
    url(r'^rse_r/(?P<id>\d+)/$',                            views.rse_room,         name='rse_room'),
    url(r'^rse_r/(?P<id>\d+)/del/$',                        views.rse_room_del,     name='rse_room_del'),
    url(r'^rsed_r/(?P<id>\d+)/$',                           views.rsed_room,        name='rsed_room'),
    url(r'^rsed_r/(?P<id>\d+)/del/$',                       views.rsed_room_del,    name='rsed_room_del'),
    url(r'^rs_d/$',                                         views.rs_dow_auto,      name='rs_dow_auto'),
    url(r'^rs_d/(?P<rs_id>\d+)/(?P<dow_id>\d+)/$',          views.rs_dow,           name='rs_dow'),
    url(r'^rse_d/(?P<id>\d+)/$',                            views.rse_dow,          name='rse_dow'),
    url(r'^rse_d/(?P<id>\d+)/del/$',                        views.rse_dow_del,      name='rse_dow_del'),
    url(r'^rsed_d/(?P<id>\d+)/$',                           views.rsed_dow,         name='rsed_dow'),
    url(r'^rsed_d/(?P<id>\d+)/del/$',                       views.rsed_dow_del,     name='rsed_dow_del'),
    url(r'^ticket/$',                                       views.ticket_list,      name='ticket_list'),
    url(r'^ticket/(?P<id>\d+)/$',	                        views.ticket_view,      name='ticket_view'),
    url(r'^ticket_t/$',                                     views.ticket_table_auto,name='ticket_table_auto'),
    url(r'^ticket_t/(?P<id>\d+)/(?P<date>\d{6})/$',         views.ticket_table,     name='ticket_table'),
    url(r'^ticket_t/(?P<id>\d+)/$',                         views.ticket,           name='ticket'),
    url(r'^ticket_t/(?P<id>\d+)/del/$',                     views.ticket_del,       name='ticket_del'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
#from dajaxice.core import dajaxice_autodiscover, dajaxice_config    # dajaxice

import views
admin.autodiscover()
#dajaxice_autodiscover() # dajaxice

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^patient/', include('patient.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^ref/', include('ref.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login),
    url(r'^logout$', logout),
    #url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),    # dajaxice
)

employee/models.py
# -*- coding: utf-8 -*-
'''
Employee
'''

from django.db import models
from django.conf import settings

from core.models import Person
from enum.models import DOW

import datetime, re

class   Department(models.Model):
    name    = models.CharField(max_length=255, unique=True, verbose_name=u'Наименование')

    class   Meta:
        ordering                = ('name', )
        verbose_name            = u'Отделение'
        verbose_name_plural     = u'Отделения'

    def     __unicode__(self):
        return self.name

class   Room(models.Model):
    '''
    '''
    id      	= models.PositiveIntegerField(primary_key=True, verbose_name=u'Номер')
    department	= models.ForeignKey(Department, related_name='rooms', verbose_name=u'Отделение')

    class   Meta:
        ordering                = ('id', )
        verbose_name            = u'Кабинет'
        verbose_name_plural     = u'Кабинеты'

    def     __unicode__(self):
        return '%02d' % self.id

class   Specialty(models.Model):
    name    = models.CharField(max_length=255, unique=True, verbose_name=u'Наименование')
    department	= models.ForeignKey(Department, related_name='specialties', verbose_name=u'Отделение')
    timeout = models.PositiveIntegerField(null=True, blank=True, verbose_name=u'Прием, мин.')

    class   Meta:
        ordering                = ('name', )
        verbose_name            = u'Специальность'
        verbose_name_plural     = u'Специальности'

    def     __unicode__(self):
        return self.name

    def     get_name_wrapped(self):
        #print re.findall('\w+', self.name)
        #return re.findall(r"\w+", self.name)
        return self.name.replace('-', ' ').split(' ')

class   Employee(models.Model):
    person      = models.OneToOneField(Person, verbose_name=u'Людь')
    specialty	= models.ManyToManyField(Specialty, through='EmployeeSpecialty')

    class   Meta:
        ordering                = ('person', )
        verbose_name            = u'Сотрудник'
        verbose_name_plural     = u'Сотрудники'

    def     __unicode__(self):
        retvalue = self.person.lastname + ' ' + self.person.firstname[0] + '.'
        midname = self.person.midname
        if midname:
            retvalue += (' ' + midname[0] + '.')
        return retvalue

class   EmployeeSpecialty(models.Model):
    employee	= models.ForeignKey(Employee, related_name='specialties', verbose_name=u'Врач')
    specialty	= models.ForeignKey(Specialty, related_name='employees', verbose_name=u'Специальность')
    rate        = models.DecimalField(blank=True, null=True, max_digits=3, decimal_places=2, verbose_name=u'Ставка')

    class   Meta:
        ordering                = ('employee', 'specialty')
        unique_together         = (('employee', 'specialty'),)
        verbose_name            = u'Должность сотрудника'
        verbose_name_plural     = u'Должности сотрудников'

    def     __unicode__(self):
        return '%s (%s)' % (self.specialty, self.employee)

class   StaffList(models.Model):
    begdate   = models.DateField(unique=True, default=datetime.datetime.today(), verbose_name=u'Действительно с')

    class   Meta:
        ordering                = ('begdate', )
        verbose_name            = u'Штатное расписание'
        verbose_name_plural     = u'Штатные расписания'

    def     __unicode__(self):
        return str(self.begdate)

class   StaffListEntry(models.Model):
    stafflist	= models.ForeignKey(StaffList, related_name='staves', verbose_name=u'ШР')
    specialty	= models.ForeignKey(Specialty, related_name='+', verbose_name=u'Специальность')
    qty     	= models.DecimalField(max_digits=5, decimal_places=2, verbose_name=u'Ставок')

    class   Meta:
        ordering                = ('stafflist', 'specialty')
        unique_together         = (('stafflist', 'specialty'),)
        verbose_name            = u'Штатное расписание'
        verbose_name_plural     = u'Штатные расписания'

    def     __unicode__(self):
        return '%s: %s - %d' % (self.stafflist, self.specialty, self.qty)

class   RoomSchedule(models.Model):
    begdate   = models.DateField(unique=True, default=datetime.datetime.today(), verbose_name=u'Действительно с')

    class   Meta:
        ordering                = ('begdate', )
        verbose_name            = u'График кабинетов'
        verbose_name_plural     = u'Графики кабинетов'

    def     __unicode__(self):
        return str(self.begdate)

class   RoomScheduleEntry(models.Model):
    schedule    = models.ForeignKey(RoomSchedule, related_name='entries', verbose_name=u'ГК')
    room        = models.ForeignKey(Room, related_name='+', verbose_name=u'Кабинет')
    dow         = models.ForeignKey(DOW, related_name='+', verbose_name=u'День')
    specialty   = models.ForeignKey(Specialty, related_name='rsentries', verbose_name=u'Специальность')
    begtime     = models.PositiveIntegerField(verbose_name=u'с')
    endtime     = models.PositiveIntegerField(verbose_name=u'по')

    class   Meta:
        ordering                = ('schedule', 'room', 'dow', 'begtime')
        verbose_name            = u'Слот кабинета'
        verbose_name_plural     = u'Слоты кабинетов'

    def     __unicode__(self):
        return '%s, каб.№%d: %s %02d:%02d-%02d:%02d - %s' % (self.schedule, self.room.pk, self.dow, self.begtime/60, self.begtime%60, self.endtime/60, self.endtime%60, self.specialty.name)

    def     __min2str(self, m):
        return '%02d:%02d' % (m/60, m%60)

    def     get_begstr(self):
        return self.__min2str(self.begtime)

    def     get_endstr(self):
        return self.__min2str(self.endtime)

    def     __min2time(self, m):
        return datetime.time(m/60, m%60)

    def     get_begtime(self):
        return self.__min2time(self.begtime)

    def     get_endtime(self):
        return self.__min2time(self.endtime)

class   RoomScheduleEntryDoc(models.Model):
    rse         = models.ForeignKey(RoomScheduleEntry, related_name='docs', verbose_name=u'Слот')
    doc         = models.ForeignKey(Employee, related_name='+', verbose_name=u'Доктор')
    begtime     = models.PositiveIntegerField(verbose_name=u'с')
    endtime     = models.PositiveIntegerField(verbose_name=u'по')

    class   Meta:
        ordering                = ('rse', 'doc', 'begtime')
        verbose_name            = u'Слот врача'
        verbose_name_plural     = u'Слоты врачей'

    def     __unicode__(self):
        return '%s: %s' % (str(self.rse), str(self.doc))

    def     __min2str(self, m):
        return '%02d:%02d' % (m/60, m%60)

    def     get_begstr(self):
        return self.__min2str(self.rse.begtime + self.begtime)

    def     get_endstr(self):
        return self.__min2str(self.rse.begtime + self.endtime)

    def     __min2time(self, m):
        return datetime.time(m/60, m%60)

    def     get_begtime(self):
        return self.__min2time(self.rse.begtime + self.begtime)

    def     get_endtime(self):
        return self.__min2time(self.rse.begtime + self.endtime)

class   Ticket(models.Model):
    '''
    TODO:
    - patient => fio+birthdate
    - rse -> room | doc
    - date+begtime+endtime=>datetime+minutes
    http://gorzdrav.spb.ru/signup/free/ - ФИО, birthdate > Specialty (специализация врача) > врач > datetime (free; на неделю вперед)
    '''
    specialty   = models.ForeignKey(Specialty, related_name='tickets', verbose_name=u'Специальность')
    date        = models.DateField(verbose_name=u'Дата')
    room        = models.ForeignKey(Room, related_name='tickets', verbose_name=u'Кабинет')
    begtime     = models.TimeField(verbose_name=u'с')
    endtime     = models.TimeField(verbose_name=u'по')
    #begtime     = models.PositiveIntegerField(verbose_name=u'с')
    #endtime     = models.PositiveIntegerField(verbose_name=u'по')
    lastname    = models.CharField(max_length=32, verbose_name=u'Фамилия')
    firstname   = models.CharField(max_length=32, verbose_name=u'Имя')
    midname     = models.CharField(max_length=32, blank=True, verbose_name=u'Отчество')
    birthdate   = models.DateField(verbose_name=u'Дата рождения')

    class   Meta:
        ordering                = ('date', 'begtime', 'specialty', 'room')
        verbose_name            = u'Талончик'
        verbose_name_plural     = u'Талончики'

    def     __unicode__(self):
        return '%s %s %s - %s' % (self.date, self.begtime, self.specialty, self.lastname)

templates/employee/base.html
{% extends "base.html" %}
{% block title %} ??? {% endblock %}
{% block header %} ??? {% endblock %}
{% block css %}
p.colselector {
    margin: 4px 0;
    text-align: center;
}
p.colselector > span {
    border: 1px solid grey;
    border-radius: 4px;
    padding: 2px 4px;
    margin-right: 2px;
}
p.colselector .active {
    background-color: silver;
}
p.colselector a:link {
    color: black;
    text-decoration: none;
}
p.colselector a:visited {
    color: black;
    text-decoration: none;
}
{% endblock %}

templates/employee/employee_detail.html
{% extends "employee/base.html" %}
{% block title %} {{ super() }}: Сотрудник: {{ object.person }} {% endblock %}
{% block header %} <a href="{{ url_for('employee.views.employee_list') }}"> Сотрудник </a> {% endblock %}
{% block body_main %}
<p> ID: {{ object.pk }} </p>
<p> Фамилия: {{ object.person.lastname }} </p>
{% endblock %}

templates/employee/employee_list.html
{% extends "employee/base.html" %}
{% block title %} {{ super() }}: Сотрудники {% endblock %}
{% block header %}
  {% set pager_url = url_for('employee.views.employee_list') %}
  {% set pager_title = 'Сотрудники' %}
  {% include "paginator.html" with context %}
{% endblock %}
 
{% block body_main %}
 {% for object in object_list %}
  <p style="padding: 0; margin: 0"> <a href="{{ url_for('employee.views.employee_view', object.pk) }}"> {{ object }} </a> </p>
 {% endfor %}
{% endblock %}

templates/employee/rs_base.html
{% extends "employee/base.html" %}
{% block js %}
  <script type="text/javascript">
      function refresh_svg() {
        var svg=document.getElementById("thesvg");
        svg.height.baseVal.value = document.getElementsByTagName("body")[0].getBoundingClientRect().bottom - svg.getBoundingClientRect().top - 4;
      }
  </script>
{% endblock %}
{% block jsready %}
    {{ super() }}
    refresh_svg();
    document.getElementsByTagName("body")[0].setAttribute('onresize', 'refresh_svg();');
    $(".hhmm>input").mask("99:99");
{% endblock %}
{% block css %}
    {{ super() }}
    form :disabled {
        color: black; 
    }
{% endblock %}
{% block body_main %}
  <div id="header">
    {% block rs_head %}
    {% endblock %}
  </div>
  <table id="thetable">
    <tr>
      <td id="leftmenu" class="thecell" style="vertical-align: top">
        {% block rs_leftmenu %}
        {% endblock %}
      </td>
      <td id="canvas" class="thecell">  <!-- set height="1234" for compatibility-->
{% block svg %}
{% endblock %}
      </td>
    </tr>
  </table>
{% endblock %}

templates/employee/rs_room.html
{#Режим просмотра всех "слотов" занятости кабинетов. Можно добавить новый слот (форма вверху). Для изменения/удаления слота или врача в нем кликните по нужному прямоугольнику.#}
{% extends "employee/rs_base.html" %}
{% block title %} График занятости кабинета {% endblock %}
{% block header %} График занятости кабинета № {{ room.pk }} {% endblock %}
{% block rs_head %}
  <p class="colselector">
  {% for i in rooms %}
    {% if i == room %}
      <span class="active">{{ i }}</span>
    {% else %}
      <span><a href="{{ url_for('rs_room', rs.id, i.pk) }}">{{ i }}</a></span>
    {% endif %}
  {% endfor %}
  (с {{ rs.begdate|date }})
  </p>
{% endblock %}
{% block rs_leftmenu %}
  {% block rs %}
  <form method="post" action=".">
    {{ form_rse.non_field_errors() }}
    {% for hidden in form_rse.hidden_fields() %}
      {{ hidden }}
    {% endfor %}
    <table>
      <tr>
        <td> {{ form_rse.dow }} </td>
        <td class="hhmm"> {{ form_rse.begtime }} </td>
        <td> - </td>
        <td class="hhmm"> {{ form_rse.endtime }} </td>
      </tr>
      <tr>
        <td> </td>
        <td> {{ form_rse.begtime.errors }} </td>
        <td> </td>
        <td> {{ form_rse.endtime.errors }} </td>
      </tr>
      <tr>
        <td colspan="4"> {{ form_rse.specialty }} </td>
      </tr>
    </table>
    <button type="submit" title="Add/Save" name="submit_rse"> &radic; </button>
    <a href="."> <button type="button" title="Cancel/Clear"> x </button> </a>
    {% block delbutton %}
    {% endblock %}
  </form>
  {% endblock %}
  {% block docs %}
  {% endblock %}
{% endblock %}

{% block svg %}
    {{ svg_room(room) }}
{% endblock %}

templates/employee/rs_view.html
{% extends "employee/rs_base.html" %}
{% block jsready %}
  {{ super() }}
  $("#id_begtime").mask("99:99");
  $("#id_endtime").mask("99:99");
{% endblock %}
{% block rs_head %}
  <p style="margin: 0"> График кабинета (с {{ rs.begdate|date }}):
  {% for i in rooms %}
    {% if i == room %}
      <span style="border: 1px solid grey; margin-left: 2px; background-color: silver;"> {{ i }} </span>
    {% else %}
      <a href="{{ url_for('rs_room', rs.id, i.pk) }}" style="border: 1px solid grey; margin-left: 2px;"> {{ i }} </a>
    {% endif %}
  {% endfor %} </p>
{% endblock %}
{% block rs_leftmenu %}
  <form method="post" action=".">
    {{ form.non_field_errors() }}
    {% for hidden in form.hidden_fields() %}
      {{ hidden }}
    {% endfor %}
    <table>
      <tr>
        <td> {{ form.dow }} </td>
        <td> {{ form.begtime }} </td>
        <td> - </td>
        <td> {{ form.endtime }} </td>
      </tr>
      <tr>
        <td/>
        <td> {{ form.begtime.errors }} </td>
        <td/>
        <td> {{ form.endtime.errors }} </td>
      </tr>
      <tr>
        <td colspan="4"> {{ form.specialty }} </td>
      </tr>
    </table>
    <button type="submit" title="Add/Save"> &radic; </button>
    <a href="."> <button type="button" title="Cancel/Clear"> x </button> </a>
    {% if rse %}
      <a href="{{ url_for('rse_room_del', rse.pk) }}"> <button type="button" title="Удалить"> - </button> </a>
    {% endif %}
  </form>
{% endblock %}
{% block rs_hgrid %}
  {% for item in dows %}
	  {% set x = hx + (loop.index0 * dx) %}
    <!-- grid -->
	  <line x1="{{x}}%" y1="0" y2="100%" x2="{{x}}%"/>
    <g class="hcenter">
      <a xlink:href="{{ url_for('rs_dow', rs.id, item.pk) }}" xlink:title="ГК для {{ item }}">
        <text x="{{x+(dx/2.0)}}%" y="0"> <tspan dy="1.5ex"> {{ item }} </tspan> </text>
      </a>
    </g>
    <!-- slots -->
    <g class="occupy">
      {% for entry in rses.filter(dow=item) %}
        {% set y = hy+(((entry.begtime/60.0)-hbeg)*dy) %}
        <a xlink:href="{{ url_for('rse_room', entry.pk) }}">
          <rect
            x="{{x}}%"
            y="{{y}}%"
            width="{{dx}}%"
            height="{{(entry.endtime-entry.begtime)/60.0*dy}}%"
            rx="3" ry="3"
            {% if rse and (rse.id == entry.pk) %} style="fill: yellow" {% endif %}
          />
          {% set xt = x+(dx/2.0) %}
          <text x="{{xt}}%" y="{{y}}%">
            {% for t in entry.specialty.get_name_wrapped() %}
              <tspan x="{{xt}}%" dy="1.5ex"> {{ t }} </tspan>
            {% endfor %}
          </text>
        </a>
      {% endfor %}
    </g>
  {% endfor %}
{% endblock %}

templates/employee/rse_room.html
{#Режим редактирования слота. Выделенный слот можно изменить или удалить (верхняя форма). Или добавить нового врача (нижняя форма). Для изменения/удаления врача кликните по нему. Для возврата в общий график еще раз кликните по выделенному слоту. #}
{% extends "employee/rs_room.html" %}

{% block delbutton %}
  <a href="{{ url_for('rse_room_del', rse.pk) }}"> <button type="button" title="Удалить"> - </button> </a>
{% endblock %}

{% block docs %}
  <table border="1" class="thick" style="margin-top: 1em" width="100%">
  <caption style="border-top: 1px solid black; background-color: wheat"> Врачи: </caption>
  <tr> <th> с </th> <th> по </th> <th> кто </th> </tr>
  {% for doc in rse.docs.all() %}
  <tr>
    <td> {{ doc.get_begstr() }} </td>
    <td> {{ doc.get_endstr() }} </td>
    <td> {{ doc.doc.person.lastname }} </td>
  </tr>
  {% endfor %}
  </table>
  <form method="post" action=".">
  <table  border="1" class="thick" style="margin-top: 1em" width="100%">
  <caption style="border-top: 1px solid black; background-color: wheat"> Новый: </caption>
  {{ form_rsed.as_table() }}
  </table>
  <button type="submit" title="Add/Save" name="submit_rsed"> &radic; </button>
  <a href="."> <button type="button" title="Cancel/Clear"> x </button> </a>
  </form>
{% endblock %}

{% block svg %}
    {{ svg_room(room, rse) }}
{% endblock %}

templates/employee/rsed_room.html
{% extends "employee/rse_room.html" %}

{% block rs %}
  <table border="0">
  <tr>
    <td> {{ rse.dow.name }} </td>
    <td> {{ rse.get_begstr() }} </td>
    <td> - </td>
    <td> {{ rse.get_endstr() }} </td>
  </tr>
  <tr> <td colspan="4"> {{ rse.specialty.name }} </td> </tr>
  </table>
{% endblock %}

{% block docs %}
  <table border="1" class="thick" style="margin-top: 1em" width="100%">
  <caption style="border-top: 1px solid black; background-color: wheat"> Врачи: </caption>
  <tr> <th> с </th> <th> по </th> <th> кто </th> </tr>
  {% for doc in rse.docs.exclude(pk=rsed.pk) %}
  <tr>
    <td> {{ doc.get_begstr() }} </td>
    <td> {{ doc.get_endstr() }} </td>
    <td> {{ doc.doc.person.lastname }} </td>
  </tr>
  {% endfor %}
  </table>
  <form method="post" action=".">
  <table  border="1" class="thick" style="margin-top: 1em" width="100%">
  <caption style="border-top: 1px solid black; background-color: wheat"> Изменить: </caption>
  {{ form_rsed.as_table() }}
  </table>
  <button type="submit" title="Save"> &radic; </button>
  <a href="."> <button type="button" title="Reload"> x </button> </a>
  <a href="{{ url_for('rsed_room_del', rsed.pk) }}"> <button type="button" title="Удалить"> - </button> </a>
  </form>
{% endblock %}

{% block svg %}
    {{ svg_room(room, rsed) }}
{% endblock %}

templates/employee/staff_add.html
{% extends "employee/base.html" %}
{% block body_main %}
<form method="post" action="">
<p> Добавить ставок для специальности &quot;{{ spec.name }}&quot; с {{ stafflist.begdate|date }}:
{{ form.as_p() }}
<button type="submit"> OK </button>
<a href="{{ url_for('stafflist_view', stafflist.id) }}"> <button type="button"> Cancel </button> </a>
</form>
{% endblock %}

templates/employee/staff_edit.html
{% extends "employee/base.html" %}
{% block body_main %}
<form method="post" action="">
<p> Ставок для специальности &quot;{{ sle.specialty.name }}&quot; с {{ sle.stafflist.begdate }}:
{{ form.as_p() }}
<button type="submit"> OK </button>
<a href="{{ url_for('stafflist_view', sle.stafflist.pk) }}"> <button type="button"> Cancel </button> </a>
<a href="{{ url_for('staff_del', sle.pk) }}"> <button type="button"> Delete </button> </a>
</form>
{% endblock %}

templates/employee/ticket_detail.html
{% extends "employee/base.html" %}
{% block title %} {{ super() }}: Талончик: {{ object }} {% endblock %}
{% block header %} <a href="{{ url_for('employee.views.ticket_list') }}"> Талончик </a> {% endblock %}
{% block body_main %}
<table border="1" class="thick">
  <tr> <th> Дата </th> <td> {{ object.date }} </td> </tr>
  <tr> <th> Начало </th> <td> {{ object.begtime }} </td> </tr>
  <tr> <th> Конец </th> <td> {{ object.endtime }} </td> </tr>
  <tr> <th> Специальность </th> <td> {{ object.specialty }} </td> </tr>
  <tr> <th> Пациент </th> <td> {{ object.person }} </td> </tr>
  <tr> <th> Слот </th> <td> {{ object.rse }} </td> </tr>
</table>
{% endblock %}

templates/employee/ticket_table.html
{% extends "employee/rs_base.html" %}
{# block jsready %}
    {{ super() }}
    $("#id_begtime").mask("99:99");
    $("#id_endtime").mask("99:99");
    $("#id_birthdate").mask("99.99.9999");
{% endblock #}
{% block title %} Талончики {% endblock %}
{% block header %} Талончики: {{ spec.name }}, {{ date }} {% endblock %}

{% block css %}
    table.calendar {
        border-collapse: collapse;
        border: 1px solid black;
        width: 100%;
    }
    table.calendar caption {
        font: bold 10pt sans-serif;
        text-align: center;
    }
    table.calendar th {
        font: normal 10pt sans-serif;
        text-align: center;
    }
    table.calendar td {
        border: 1px dotted black;
        font: bold 8pt sans-serif;
        text-align: center;
        padding: 0;
    }
    table.calendar tbody td a div {
        /*width:  24px;*/
        height: 19px;
        padding: 5px 0 0;
    }
    table.calendar tbody td a:link {
        color: black;
        text-decoration: none;
    }
    table.calendar tbody td a:visited {
        color: black;
        text-decoration: none;
    }
{% endblock %}

{% block jsready %}
{% endblock %}

{% block rs_head %}
{% endblock %}

{% block rs_leftmenu %}
  <!-- specialty: -->
  <form method="post" action=".">
  <p style="padding: 0; margin: 0;">
  {{ form_spec.specialty }}
  <button type="submit" name="submit_spec" title="Set new specialty"> &gt; </button>
  </p>
  </form>
  <!-- /specialty -->
  <!-- calendar: -->
  <table class="calendar">
    <thead>
      <tr>
        <th> <a href=""> <img src="{{ STATIC_URL }}img/16/icon-backward.png" alt="prev"/> </a> </th>
        <th colspan="5" class="bb"> <b> {{ date.month }}/{{ date.year }} </b> </th>
        <th> <a href=""> <img src="{{ STATIC_URL }}img/16/icon-forward.png" alt="next"/> </a> </th>
      </tr>
      <tr> <th> П </th> <th> В </th> <th> С </th> <th> Ч </th> <th> П </th> <th> С </th> <th> В </th> </tr>
    </thead>
    <tbody>
    {% for week in cal.monthdatescalendar(date.year, date.month) %}
        <tr>
        {% for d in week %}
            <td {% if d == date %} style="background-color: yellow" {% endif %}>
            <a href="{{ url_for('ticket_table', spec.pk, d.strftime('%y%m%d')) }}">
            <div> {{ d.day }} </div> </a> </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
  </table>
  <!-- /calendar -->
  <!-- form: -->
  <form method="post" action=".">
  <table>
  {{ form_ticket.as_table() }}
  </table>
  <button type="submit" title="Ok"> &radic; </button>
  <a href="."> <button type="button" title="Reload"> x </button> </a>
  {% if ticket %}
  <a href="{{ url_for('ticket_del', ticket.pk) }}"> <button type="button" title="Delete"> - </button> </a>
  {% endif %}
  </form>
  <!-- /form -->
{% endblock %}
{% block svg %}
  {{ svg_tickets(spec, date, ticket) }}
{% endblock %}